language: node_js
node_js:
  - node
  - "lts/*"
env:
  global:
    - NODE_NEV="production"

cache:
  yarn: true

branches:
  only:
    - master
    - develop
    - /^release\/.*$/

notifications:
  email: false
